title: V_sidde Markets
author: End-debug
email: your-acoussounds@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Pathing the way to a better and simpler ecommerce platform for the everday Joe and Themba out there.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme : minima
